name: xyz
main: unerds\xyz\xyz
version: 1.0.4
api: [3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9]

load: POSTWORLD
author: unerds
description: command to display player coordinates
website: github.com/unerds
commands:
 xyz:
  description: Returns Player Coordinates
  usage: "/xyz"
  permission: xyz.command.xyz